call go.bat example0.txt
call go.bat example1.txt
call go.bat example2.txt
call go.bat example3.txt
call go.bat example3-1.txt
call go.bat example4.txt
call go.bat example5.txt
call go.bat example6.txt
call go.bat example7.txt
call go.bat example8.txt
call go.bat example9.txt
call go.bat example9-1.txt
call go.bat example9-2.txt
call go.bat example10.txt
call go.bat example11.txt
call go.bat example12.txt
call go.bat example13.txt
call go.bat example14.txt
call go.bat example15.txt
call go.bat example16.txt